// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgitlab

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockModuleRegistryAdapter creates a new instance of MockModuleRegistryAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModuleRegistryAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModuleRegistryAdapter {
	mock := &MockModuleRegistryAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModuleRegistryAdapter is an autogenerated mock type for the ModuleRegistryAdapter type
type MockModuleRegistryAdapter struct {
	mock.Mock
}

type MockModuleRegistryAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModuleRegistryAdapter) EXPECT() *MockModuleRegistryAdapter_Expecter {
	return &MockModuleRegistryAdapter_Expecter{mock: &_m.Mock}
}

// UploadModule provides a mock function for the type MockModuleRegistryAdapter
func (_mock *MockModuleRegistryAdapter) UploadModule(ctx context.Context, name string, system string, version string, archive io.Reader) error {
	ret := _mock.Called(ctx, name, system, version, archive)

	if len(ret) == 0 {
		panic("no return value specified for UploadModule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, io.Reader) error); ok {
		r0 = returnFunc(ctx, name, system, version, archive)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockModuleRegistryAdapter_UploadModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadModule'
type MockModuleRegistryAdapter_UploadModule_Call struct {
	*mock.Call
}

// UploadModule is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - system string
//   - version string
//   - archive io.Reader
func (_e *MockModuleRegistryAdapter_Expecter) UploadModule(ctx any, name any, system any, version any, archive any) *MockModuleRegistryAdapter_UploadModule_Call {
	return &MockModuleRegistryAdapter_UploadModule_Call{Call: _e.mock.On("UploadModule", ctx, name, system, version, archive)}
}

func (_c *MockModuleRegistryAdapter_UploadModule_Call) Run(run func(ctx context.Context, name string, system string, version string, archive io.Reader)) *MockModuleRegistryAdapter_UploadModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 io.Reader
		if args[4] != nil {
			arg4 = args[4].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockModuleRegistryAdapter_UploadModule_Call) Return(err error) *MockModuleRegistryAdapter_UploadModule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockModuleRegistryAdapter_UploadModule_Call) RunAndReturn(run func(ctx context.Context, name string, system string, version string, archive io.Reader) error) *MockModuleRegistryAdapter_UploadModule_Call {
	_c.Call.Return(run)
	return _c
}
