// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgitlab

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/gitlab-org/api/client-go/v2"
)

// NewMockNotes creates a new instance of MockNotes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotes(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotes {
	mock := &MockNotes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotes is an autogenerated mock type for the Notes type
type MockNotes struct {
	mock.Mock
}

type MockNotes_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotes) EXPECT() *MockNotes_Expecter {
	return &MockNotes_Expecter{mock: &_m.Mock}
}

// CreateMergeRequestNote provides a mock function for the type MockNotes
func (_mock *MockNotes) CreateMergeRequestNote(pid any, mergeRequest int64, opt *gitlab.CreateMergeRequestNoteOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Note, *gitlab.Response, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(pid, mergeRequest, opt, options)
	} else {
		tmpRet = _mock.Called(pid, mergeRequest, opt)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateMergeRequestNote")
	}

	var r0 *gitlab.Note
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(any, int64, *gitlab.CreateMergeRequestNoteOptions, ...gitlab.RequestOptionFunc) (*gitlab.Note, *gitlab.Response, error)); ok {
		return returnFunc(pid, mergeRequest, opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(any, int64, *gitlab.CreateMergeRequestNoteOptions, ...gitlab.RequestOptionFunc) *gitlab.Note); ok {
		r0 = returnFunc(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any, int64, *gitlab.CreateMergeRequestNoteOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(any, int64, *gitlab.CreateMergeRequestNoteOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, mergeRequest, opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNotes_CreateMergeRequestNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMergeRequestNote'
type MockNotes_CreateMergeRequestNote_Call struct {
	*mock.Call
}

// CreateMergeRequestNote is a helper method to define mock.On call
//   - pid any
//   - mergeRequest int64
//   - opt *gitlab.CreateMergeRequestNoteOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockNotes_Expecter) CreateMergeRequestNote(pid any, mergeRequest any, opt any, options ...any) *MockNotes_CreateMergeRequestNote_Call {
	return &MockNotes_CreateMergeRequestNote_Call{Call: _e.mock.On("CreateMergeRequestNote",
		append([]any{pid, mergeRequest, opt}, options...)...)}
}

func (_c *MockNotes_CreateMergeRequestNote_Call) Run(run func(pid any, mergeRequest int64, opt *gitlab.CreateMergeRequestNoteOptions, options ...gitlab.RequestOptionFunc)) *MockNotes_CreateMergeRequestNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *gitlab.CreateMergeRequestNoteOptions
		if args[2] != nil {
			arg2 = args[2].(*gitlab.CreateMergeRequestNoteOptions)
		}
		var arg3 []gitlab.RequestOptionFunc
		var variadicArgs []gitlab.RequestOptionFunc
		if len(args) > 3 {
			variadicArgs = args[3].([]gitlab.RequestOptionFunc)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockNotes_CreateMergeRequestNote_Call) Return(note *gitlab.Note, response *gitlab.Response, err error) *MockNotes_CreateMergeRequestNote_Call {
	_c.Call.Return(note, response, err)
	return _c
}

func (_c *MockNotes_CreateMergeRequestNote_Call) RunAndReturn(run func(pid any, mergeRequest int64, opt *gitlab.CreateMergeRequestNoteOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Note, *gitlab.Response, error)) *MockNotes_CreateMergeRequestNote_Call {
	_c.Call.Return(run)
	return _c
}

// ListMergeRequestNotes provides a mock function for the type MockNotes
func (_mock *MockNotes) ListMergeRequestNotes(pid any, mergeRequest int64, opt *gitlab.ListMergeRequestNotesOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Note, *gitlab.Response, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(pid, mergeRequest, opt, options)
	} else {
		tmpRet = _mock.Called(pid, mergeRequest, opt)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListMergeRequestNotes")
	}

	var r0 []*gitlab.Note
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(any, int64, *gitlab.ListMergeRequestNotesOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.Note, *gitlab.Response, error)); ok {
		return returnFunc(pid, mergeRequest, opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(any, int64, *gitlab.ListMergeRequestNotesOptions, ...gitlab.RequestOptionFunc) []*gitlab.Note); ok {
		r0 = returnFunc(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any, int64, *gitlab.ListMergeRequestNotesOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, mergeRequest, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(any, int64, *gitlab.ListMergeRequestNotesOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, mergeRequest, opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNotes_ListMergeRequestNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMergeRequestNotes'
type MockNotes_ListMergeRequestNotes_Call struct {
	*mock.Call
}

// ListMergeRequestNotes is a helper method to define mock.On call
//   - pid any
//   - mergeRequest int64
//   - opt *gitlab.ListMergeRequestNotesOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockNotes_Expecter) ListMergeRequestNotes(pid any, mergeRequest any, opt any, options ...any) *MockNotes_ListMergeRequestNotes_Call {
	return &MockNotes_ListMergeRequestNotes_Call{Call: _e.mock.On("ListMergeRequestNotes",
		append([]any{pid, mergeRequest, opt}, options...)...)}
}

func (_c *MockNotes_ListMergeRequestNotes_Call) Run(run func(pid any, mergeRequest int64, opt *gitlab.ListMergeRequestNotesOptions, options ...gitlab.RequestOptionFunc)) *MockNotes_ListMergeRequestNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *gitlab.ListMergeRequestNotesOptions
		if args[2] != nil {
			arg2 = args[2].(*gitlab.ListMergeRequestNotesOptions)
		}
		var arg3 []gitlab.RequestOptionFunc
		var variadicArgs []gitlab.RequestOptionFunc
		if len(args) > 3 {
			variadicArgs = args[3].([]gitlab.RequestOptionFunc)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockNotes_ListMergeRequestNotes_Call) Return(notes []*gitlab.Note, response *gitlab.Response, err error) *MockNotes_ListMergeRequestNotes_Call {
	_c.Call.Return(notes, response, err)
	return _c
}

func (_c *MockNotes_ListMergeRequestNotes_Call) RunAndReturn(run func(pid any, mergeRequest int64, opt *gitlab.ListMergeRequestNotesOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Note, *gitlab.Response, error)) *MockNotes_ListMergeRequestNotes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMergeRequestNote provides a mock function for the type MockNotes
func (_mock *MockNotes) UpdateMergeRequestNote(pid any, mergeRequest int64, note int64, opt *gitlab.UpdateMergeRequestNoteOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Note, *gitlab.Response, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(pid, mergeRequest, note, opt, options)
	} else {
		tmpRet = _mock.Called(pid, mergeRequest, note, opt)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateMergeRequestNote")
	}

	var r0 *gitlab.Note
	var r1 *gitlab.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(any, int64, int64, *gitlab.UpdateMergeRequestNoteOptions, ...gitlab.RequestOptionFunc) (*gitlab.Note, *gitlab.Response, error)); ok {
		return returnFunc(pid, mergeRequest, note, opt, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(any, int64, int64, *gitlab.UpdateMergeRequestNoteOptions, ...gitlab.RequestOptionFunc) *gitlab.Note); ok {
		r0 = returnFunc(pid, mergeRequest, note, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any, int64, int64, *gitlab.UpdateMergeRequestNoteOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = returnFunc(pid, mergeRequest, note, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(any, int64, int64, *gitlab.UpdateMergeRequestNoteOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = returnFunc(pid, mergeRequest, note, opt, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNotes_UpdateMergeRequestNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMergeRequestNote'
type MockNotes_UpdateMergeRequestNote_Call struct {
	*mock.Call
}

// UpdateMergeRequestNote is a helper method to define mock.On call
//   - pid any
//   - mergeRequest int64
//   - note int64
//   - opt *gitlab.UpdateMergeRequestNoteOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *MockNotes_Expecter) UpdateMergeRequestNote(pid any, mergeRequest any, note any, opt any, options ...any) *MockNotes_UpdateMergeRequestNote_Call {
	return &MockNotes_UpdateMergeRequestNote_Call{Call: _e.mock.On("UpdateMergeRequestNote",
		append([]any{pid, mergeRequest, note, opt}, options...)...)}
}

func (_c *MockNotes_UpdateMergeRequestNote_Call) Run(run func(pid any, mergeRequest int64, note int64, opt *gitlab.UpdateMergeRequestNoteOptions, options ...gitlab.RequestOptionFunc)) *MockNotes_UpdateMergeRequestNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *gitlab.UpdateMergeRequestNoteOptions
		if args[3] != nil {
			arg3 = args[3].(*gitlab.UpdateMergeRequestNoteOptions)
		}
		var arg4 []gitlab.RequestOptionFunc
		var variadicArgs []gitlab.RequestOptionFunc
		if len(args) > 4 {
			variadicArgs = args[4].([]gitlab.RequestOptionFunc)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockNotes_UpdateMergeRequestNote_Call) Return(note1 *gitlab.Note, response *gitlab.Response, err error) *MockNotes_UpdateMergeRequestNote_Call {
	_c.Call.Return(note1, response, err)
	return _c
}

func (_c *MockNotes_UpdateMergeRequestNote_Call) RunAndReturn(run func(pid any, mergeRequest int64, note int64, opt *gitlab.UpdateMergeRequestNoteOptions, options ...gitlab.RequestOptionFunc) (*gitlab.Note, *gitlab.Response, error)) *MockNotes_UpdateMergeRequestNote_Call {
	_c.Call.Return(run)
	return _c
}
