---
spec:
  inputs:
    cwd:
      type: string
      description: The working directory of the pipe.
    container-image-name:
      type: string
      description: The name of the container image.
    container-matrix:
      type: array
      description: A matrix of containers for building images.
---
stages:
  - install
  - build
  - container

variables:
  GO_CWD: $[[inputs.cwd]]

install:
  stage: install
  image: cenk1cenk2/pipe-go2:bootstrap
  script:
    - pipe install
  artifacts:
    paths:
      - vendor/
  cache:
    - key: pipe-install
      paths:
        - vendor/
  tags:
    - amd64
    - docker

lint:
  stage: build
  image: cenk1cenk2/pipe-go2:bootstrap
  dependencies: []
  script:
    - pipe tool -- golangci-lint run --timeout 3m
  tags:
    - amd64
    - docker

build:
  stage: build
  image: cenk1cenk2/pipe-go2:bootstrap
  variables:
    GO_BUILD_BINARY_NAME: pipe
    GO_BUILD_LINKER: -w -s
    GO_BUILD_VARIABLES: |-
      main.VERSION: ${CI_COMMIT_TAG:-BUILD.${CI_COMMIT_SHORT_SHA}}.{{ now | date "2006-01-02T15:04:05Z0700" }}
    GO_BUILD_TARGETS: |-
      - os: linux
        arch: amd64
  artifacts:
    paths:
      - $GO_CWD/dist/
  script:
    - pipe build
  tags:
    - amd64
    - docker

container:
  stage: container
  image: cenk1cenk2/pipe-buildah:bootstrap
  variables:
    CONTAINER_REGISTRY_USERNAME: $DOCKERHUB_USERNAME
    CONTAINER_REGISTRY_PASSWORD: $DOCKERHUB_PASSWORD
    CONTAINER_FILE_CONTEXT: $[[inputs.cwd]]
    CONTAINER_IMAGE_NAME: $[[inputs.container-image-name]]
  parallel:
    matrix: $[[inputs.container-matrix]]
  script:
    - pipe build
  tags:
    - amd64
    - docker
