version: "2"
linters:
  default: standard
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        source: ^//\s*go:generate\s
      - linters:
          - staticcheck
        text: "ST1001:"
      - linters:
          - staticcheck
        text: "ST1005:"
      - linters:
          - staticcheck
        text: "QF1008:"
      - linters:
          - errcheck
        source: \s*defer\s+
formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    golines:
      max-len: 180
