---
# https://taskfile.dev

version: "3"

vars: {}

env:
  CGO_ENABLED: 0
  GO_VERSION: 1.25

output: prefixed

includes:
  go:
    taskfile: https://gitlab.kilic.dev/libraries/taskfiles/-/raw/main/Taskfile.go-library.yml?ref_type=heads
    flatten: true
  template:
    dir: ./_template
    taskfile: ./Taskfile.pipe.yml
  docker:
    dir: ./docker
    taskfile: ./Taskfile.pipe.yml
  markdown-toc:
    dir: ./markdown-toc
    taskfile: ./Taskfile.pipe.yml
  node:
    dir: ./node
    taskfile: ./Taskfile.pipe.yml
  select-env:
    dir: ./select-env
    taskfile: ./Taskfile.pipe.yml
  semantic-release:
    dir: ./semantic-release
    taskfile: ./Taskfile.pipe.yml
  terraform:
    dir: ./terraform
    taskfile: ./Taskfile.pipe.yml
  update-docker-hub-readme:
    dir: ./update-docker-hub-readme
    taskfile: ./Taskfile.pipe.yml

tasks:
  packages:
    internal: true
    deps:
      - task: "template:{{ .command }}"
      - task: "docker:{{ .command }}"
      - task: "markdown-toc:{{ .command }}"
      - task: "node:{{ .command }}"
      - task: "select-env:{{ .command }}"
      - task: "semantic-release:{{ .command }}"
      - task: "terraform:{{ .command }}"
      - task: "update-docker-hub-readme:{{ .command }}"

  build:
    desc: Builds all the applications.
    cmds:
      - task: packages
        vars:
          command: build

  docs:
    desc: Generates documentation for all applications.
    cmds:
      - task: packages
        vars:
          command: docs
