---
include:
  - project: devops/pipes
    file: /templates/v2/docker-manifest.gitlab-ci.yml

.docker-manifest-internal:
  extends: .docker-manifest
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_REGISTRY_USERNAME: $CI_REGISTRY_USER
    DOCKER_REGISTRY_PASSWORD: $CI_BUILD_TOKEN
