---
variables:
  PIPES_VERSION: latest

.gh-release-tracker:
  image: cenk1cenk2/pipe-gh-release-tracker:${PIPES_VERSION}
  script:
    - pipe
  artifacts:
    paths:
      - "**/.tags"
  only:
    refs:
      - master
      - main
  tags:
    - docker
