.report-status-to-github:
  variables:
    GITHUB_STATUS_PROJECT:
    GITHUB_STATUS_NAME: Gitlab
  script:
    - curl -X POST -H 'Authorization: token ${GH_TOKEN}' https://api.github.com/repos/${GITHUB_STATUS_PROJECT}/statuses/${CI_COMMIT_SHA}?state=${CI_JOB_NAME}\&context=${GITHUB_STATUS_NAME}\&target_url=${CI_PIPELINE_URL}
  environment:
    name: reporting-github
  dependencies: []

report-status-to-github-pending:
  stage: .pre
  extends:
    - .report-status-to-github

report-status-to-github-success:
  stage: .post
  extends:
    - .report-status-to-github

report-status-to-github-failed:
  stage: .post
  extends:
    - .report-status-to-github
  rules:
    - when: on_failure
