.github-status:
  image: curlimages/curl:latest
  variables:
    GIT_STRATEGY: none
  script:
    # https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28
    - |
      curl -sS -X POST -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/${GITHUB_STATUS_PROJECT}/statuses/${CI_COMMIT_SHA}" \
      -d "{\"state\":\"${GITHUB_STATUS_REPORT}\",\"target_url\":\"${CI_PIPELINE_URL}\",\"context\":\"Gitlab CI\"}"
  dependencies: []
  tags:
    - docker

github-status-pending:
  stage: .pre
  extends:
    - .github-status
  variables:
    GITHUB_STATUS_REPORT: pending

github-status-success:
  stage: .post
  extends:
    - .github-status
  variables:
    GITHUB_STATUS_REPORT: success

github-status-failed:
  stage: .post
  extends:
    - .github-status
  variables:
    GITHUB_STATUS_REPORT: failure
  rules:
    - when: on_failure
