---
variables:
  PIPES_VERSION: latest

.gitlab-artifacts-download:
  image: cenk1cenk2/pipe-gl-artifacts:${PIPES_VERSION}
  script:
    - pipe
  artifacts:
    paths:
      - "**/dist/"
  tags:
    - docker
  rules:
    - if: $PARENT_DOWNLOAD_ARTIFACTS
