---
.gitlab-artifacts-download:
  image: cenk1cenk2/pipe-gl-artifacts:${PIPES_VERSION}
  variables:
    PIPES_VERSION: latest
  script:
    - pipe
  artifacts:
    paths:
      - dist/
      - "**/dist/"
  tags:
    - docker
  rules:
    - if: $PARENT_DOWNLOAD_ARTIFACTS
