---
include:
  - project: devops/pipes
    file: /templates/v2/go-run.gitlab-ci.yml

.go-build:
  extends: .go-run
  variables:
    GO_BUILD_COMMAND: build
    GO_COMMAND_SCRIPT: $GO_BUILD_COMMAND
  artifacts:
    paths:
      - node_modules/
      - "**/node_modules/"
