---
include:
  - project: devops/pipes
    file: /templates/v2/go-run.gitlab-ci.yml

variables:
  GO_BUILD_COMMAND: build

.go-build:
  extends: .go-run
  variables:
    GO_COMMAND_SCRIPT: $GO_BUILD_COMMAND
  artifacts:
    paths:
      - "**/dist/"
