---
include:
  - project: devops/pipes
    file: /templates/v2/go-run.gitlab-ci.yml

.go-install:
  extends: .go-run
  variables:
    GO_INSTALL_COMMAND: install
    GO_COMMAND_SCRIPT: $GO_INSTALL_COMMAND
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/
