---
include:
  - project: devops/pipes
    file: /templates/v2/go-run.gitlab-ci.yml

variables:
  GO_INSTALL_COMMAND: install

.go-install:
  extends: .go-run
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
    GO_COMMAND_SCRIPT: $GO_INSTALL_COMMAND
  before_script:
    - mkdir -p .go
  artifacts:
    paths:
      - vendor/
  # cache:
  #   - key: $CI_JOB_NAME_SLUG
  #     # files:
  #     #   - go.mod
  #     #   - go.sum
  #     #   - go.work
  #     paths:
  #       - .go/pkg/mod/
