---
.go-install:
  variables:
    GO_INSTALL_COMMAND: install
    GITLAB_CI_ARCH: docker
  script:
    - task $GO_INSTALL_COMMAND
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/
  tags:
    - ${GITLAB_CI_ARCH}
