---
variables:
  GITLAB_CI_ARCH: docker
  GO_COMMAND_RUNNER: task

.go-run:
  image: cenk1cenk2/pipe-go:${GO_VERSION}
  script:
    - $GO_COMMAND_RUNNER $GO_COMMAND_SCRIPT
  when: on_success
  tags:
    - ${GITLAB_CI_ARCH}
