---
variables:
  PIPES_VERSION: latest

.markdown-toc:
  image: cenk1cenk2/pipe-markdown-toc:${PIPES_VERSION}
  script:
    - pipe
  artifacts:
    paths:
      - README.md
      - "packages/*/README.md"
  only:
    refs:
      - master
      - main
  tags:
    - docker
