---
variables:
  GITLAB_CI_ARCH: amd64

.node-run:
  image: cenk1cenk2/pipe-node:${NODE_VERSION}
  script:
    - pipe run
  cache:
    - key: node-cache
      paths:
        - node_modules/.cache
  tags:
    - ${GITLAB_CI_ARCH}
