---
variables:
  GITLAB_CI_ARCH: amd64

.node-build:
  image: cenk1cenk2/pipe-node:${NODE_VERSION}
  script:
    - pipe build
  cache:
    - key: $CI_JOB_NAME_SLUG
      paths:
        - node_modules/.cache
  artifacts:
    paths:
      - "**/dist/"
    exclude:
      - "node_modules*"
      - "node_modules/**/*"
  rules:
    - when: on_success
  tags:
    - ${GITLAB_CI_ARCH}
