---
variables:
  GITLAB_CI_ARCH: amd64

.node-install:
  image: cenk1cenk2/pipe-node:${NODE_VERSION}
  script:
    - pipe install
  artifacts:
    paths:
      - "**/node_modules/"
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - .npm/
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn/
    - key:
        files:
          - pnpm-lock.yaml
      paths:
        - .pnpm/
  rules:
    - when: on_success
  tags:
    - ${GITLAB_CI_ARCH}
