---
variables:
  GITLAB_CI_ARCH: amd64

.node-install:
  image: cenk1cenk2/pipe-node:${NODE_VERSION}
  script:
    - pipe install
  artifacts:
    paths:
      - "**/node_modules/"
  # cache:
  #   - key: $CI_JOB_NAME_SLUG-npm-cache
  #     # files:
  #     #   - package.json
  #     #   - package-lock.json
  #     paths:
  #       - .npm/
  #   - key: $CI_JOB_NAME_SLUG-yarn-cache
  #     # files:
  #     #   - package.json
  #     #   - yarn.lock
  #     paths:
  #       - .yarn/
  #   - key: $CI_JOB_NAME_SLUG-pnpm-cache
  #     # files:
  #     #   - package.json
  #     #   - pnpm-lock.yaml
  #     paths:
  #       - .pnpm/
  rules:
    - when: on_success
  tags:
    - ${GITLAB_CI_ARCH}
