---
include:
  - project: devops/pipes
    file: /templates/v2/node-run.gitlab-ci.yml

variables:
  NODE_LINT_COMMAND: lint:check

.node-lint:
  extends: .node-run
  variables:
    NODE_COMMAND_SCRIPT: $NODE_LINT_COMMAND
  when: on_success
