---
variables:
  PIPES_VERSION: latest

.release-it:
  image: cenk1cenk2/pipe-release-it:${PIPES_VERSION}
  script:
    - pipe
  dependencies: []
  artifacts:
    paths:
      - "**/.tags"
  only:
    refs:
      - master
      - main
      - alpha
      - beta
      - rc
      - next
  tags:
    - docker
