---
.semantic-release:
  image: cenk1cenk2/pipe-semantic-release:${PIPES_VERSION}
  variables:
    PIPES_VERSION: latest
    GIT_AUTHOR_NAME: semantic-release [bot]
    GIT_AUTHOR_EMAIL: gitlab@kilic.dev
    GIT_COMMITTER_NAME: semantic-release [bot]
    GIT_COMMITTER_EMAIL: gitlab@kilic.dev
  script:
    - pipe
  artifacts:
    paths:
      - .tags
      - "**/.tags"
  only:
    refs:
      - master
      - main
      - alpha
      - beta
      - rc
      - next
  tags:
    - docker
