---
variables:
  GITLAB_CI_ARCH: docker
  TF_VERSION: latest

.tf-publish:
  image: cenk1cenk2/pipe-terraform:${TF_VERSION}
  script:
    - pipe publish
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - ${GITLAB_CI_ARCH}
