---
variables:
  GITLAB_CI_ARCH: docker
  TF_VERSION: latest
  TF_ROOT: .

.terraform-install:
  image: cenk1cenk2/pipe-terraform:${TF_VERSION}
  environment:
    name: $TF_STATE_NAME
  script:
    - pipe install
  artifacts:
    paths:
      - "${TF_ROOT}/.terraform/"
  cache:
    - key: $CI_JOB_NAME_SLUG
      paths:
        - "${TF_ROOT}/.terraform/"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_OPEN_MERGE_REQUESTS # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
      when: never
    - if: $CI_COMMIT_BRANCH # If there's no open merge request, add it to a *branch* pipeline instead.
    - if: $CI_COMMIT_TAG
  tags:
    - ${GITLAB_CI_ARCH}
