---
update-docker-hub-readme:
  image: cenk1cenk2/pipe-update-docker-hub-readme:${PIPES_VERSION}
  script:
    - pipe
  variables:
    PIPES_VERSION: latest
    DOCKER_USERNAME: $DOCKERHUB_USERNAME
    DOCKER_PASSWORD: $DOCKERHUB_API_PASSWORD
  when: on_success
  only:
    refs:
      - master
      - main
      - tags
  tags:
    - docker
