variables:
  PIPES_VERSION: latest
  PARENT_DOWNLOAD_ARTIFACTS: "build"

stages:
  - prepare
  - docker

prepare:
  stage: prepare
  image: $CI_REGISTRY/devops/pipes/gitlab-pipes-gl-artifacts:${PIPES_VERSION}
  script:
    - pipe
  artifacts:
    paths:
      - dist/
      - "**/dist/"
  tags:
    - docker
  rules:
    - if: $PARENT_DOWNLOAD_ARTIFACTS

include:
  - project: devops/pipes
    file: /templates/docker-build-dockerhub.gitlab-ci.yml
    ref: main
