variables:
  PIPES_VERSION: latest
  DOCKER_REGISTRY: ""
  DOCKER_REGISTRY_USERNAME: $DOCKERHUB_USERNAME
  DOCKER_REGISTRY_PASSWORD: $DOCKERHUB_PASSWORD

manifest-docker-image:
  stage: post
  image: cenk1cenk2/pipe-docker:${PIPES_VERSION}
  script:
    - pipe manifest
  tags:
    - docker
