variables:
  PIPES_VERSION: latest
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  DOCKER_REGISTRY_PASSWORD: $CI_BUILD_TOKEN
  DOCKER_IMAGE_NAME: $CI_PROJECT_PATH/$DOCKER_IMAGE_INTERNAL_NAME
  DOCKER_IMAGE_TAGS: $CI_BUILD_REF_NAME
  DOCKERFILE_CONTEXT: "."

stages:
  - docker

build-docker-image:
  stage: docker
  image: cenk1cenk2/pipe-docker:${PIPES_VERSION}
  script:
    - pipe
  tags:
    - docker
