variables:
  PIPES_VERSION: latest
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  DOCKER_REGISTRY_PASSWORD: $CI_BUILD_TOKEN
  IMAGE_NAME: $CI_PROJECT_PATH/$DOCKER_IMAGE_NAME
  IMAGE_TAGS: $CI_BUILD_REF_NAME
  DOCKERFILE_CONTEXT: "."

stages:
  - docker

build-docker-image:
  stage: docker
  image: $CI_REGISTRY/devops/pipes/gitlab-pipes-docker:${PIPES_VERSION}
  script:
    - pipe
  tags:
    - docker
