variables:
  PIPES_VERSION: latest
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  DOCKER_REGISTRY_PASSWORD: $CI_BUILD_TOKEN

manifest-docker-image:
  stage: post
  image: cenk1cenk2/pipe-docker:${PIPES_VERSION}
  script:
    - pipe manifest
  tags:
    - docker
