variables:
  TAGS_FILE: .tags

stages:
  - publish

gh-release-tracker:
  stage: publish
  image: cenk1cenk2/pipe-gh-release-tracker:latest
  script:
    - pipe
  artifacts:
    paths:
      - .tags
      - "**/.tags"
  only:
    refs:
      - master
      - main
  tags:
    - docker
