stages:
  - track

gh-release-tracker:
  stage: track
  image: cenk1cenk2/pipe-gh-release-tracker:latest
  script:
    - pipe
  artifacts:
    paths:
      - .tags
      - "**/.tags"
  only:
    refs:
      - master
      - main
  tags:
    - docker
