variables:
  GO_IMAGE: alpine
  GO_BUILD_COMMAND: make -j4 build

build:
  stage: build
  image: golang:$GO_IMAGE
  script:
    - apk add --no-cache --no-progress make git
    - $GO_BUILD_COMMAND
  rules:
    - when: on_success
  artifacts:
    paths:
      - ./dist/
  tags:
    - docker
