variables:
  GO_BUILD_COMMAND: task build
  GITLAB_CI_ARCH: docker

build:
  stage: build
  image: cenk1cenk2/pipe-go:${GO_VERSION}
  script:
    - $GO_BUILD_COMMAND
  rules:
    - when: on_success
  artifacts:
    paths:
      - ./dist/
  tags:
    - ${GITLAB_CI_ARCH}
