variables:
  GO_INSTALL_COMMAND: task install

install:
  stage: install
  image: cenkcenk1/pipe-go:${GO_VERSION}
  script:
    - $GO_INSTALL_COMMAND
  rules:
    - when: on_success
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/
  tags:
    - docker
