variables:
  GO_IMAGE: alpine
  GO_INSTALL_COMMAND: make install

install:
  stage: install
  image: golang:$GO_IMAGE
  script:
    - apk add --no-cache --no-progress make git
    - $GO_INSTALL_COMMAND
  rules:
    - when: on_success
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/
  tags:
    - docker
