variables:
  GO_IMAGE: alpine

install:
  stage: install
  image: golang:$GO_IMAGE
  script:
    - apk add --no-cache --no-progress make git
    - make install
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/
  tags:
    - docker
