variables:
  GO_INSTALL_COMMAND: task install
  GITLAB_CI_ARCH: docker

install:
  stage: install
  image: cenk1cenk2/pipe-go:${GO_VERSION}
  script:
    - $GO_INSTALL_COMMAND
  rules:
    - when: on_success
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/
  tags:
    - ${GITLAB_CI_ARCH}
