variables:
  GO_IMAGE: alpine
  GO_INSTALL_COMMAND: task install

install:
  stage: install
  image: golang:$GO_IMAGE
  script:
    - apk add --no-cache --no-progress git
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/bin
    - $GO_INSTALL_COMMAND
  rules:
    - when: on_success
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/
  tags:
    - docker
