variables:
  GO_IMAGE: alpine
  GO_LINT_COMMAND: ""

lint:
  stage: build
  image: golang:$GO_IMAGE
  script:
    - apk add --no-cache --no-progress git
    - wget https://taskfile.dev/install.sh -O - | sh /dev/stdin -d -b /usr/bin
    - $GO_LINT_COMMAND
  tags:
    - docker
  rules:
    - if: $GO_LINT_COMMAND
