variables:
  GO_LINT_COMMAND: task lint
  GITLAB_CI_ARCH: amd64

lint:
  stage: build
  image: cenk1cenk2/pipe-go:${GO_VERSION}
  script:
    - $GO_LINT_COMMAND
  tags:
    - ${GITLAB_CI_ARCH}
  rules:
    - if: $GO_LINT_COMMAND
