variables:
  GO_IMAGE: alpine
  GO_LINT_COMMAND: ""

lint:
  stage: build
  image: golang:$GO_IMAGE
  script:
    - apk add --no-cache --no-progress make git
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -b /usr/bin
    - $GO_LINT_COMMAND
  tags:
    - docker
  rules:
    - if: $GO_LINT_COMMAND
