stages:
  - install
  - build

variables:
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  GO_VERSION: 1.19-alpine
  GITLAB_CI_ARCH: docker

include:
  - project: devops/pipes
    file: /templates/go-install.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/go-build.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/go-lint.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/go-test.gitlab-ci.yml
