stages:
  - docs

update-markdown-toc:
  stage: docs
  image: cenk1cenk2/pipe-markdown-toc:latest
  script:
    - pipe
  artifacts:
    paths:
      - README.md
      - "packages/*/README.md"
  only:
    refs:
      - master
      - main
  tags:
    - docker
