build:
  stage: build
  image: $CI_REGISTRY/devops/pipes/gitlab-pipes-node:${NODE_VERSION}
  script:
    - pipe build
  artifacts:
    paths:
      - dist/
      - "**/dist/"
  rules:
    - when: on_success
  tags:
    - docker
