build:
  stage: build
  image: cenk1cenk2/pipe-node:${NODE_VERSION}
  script:
    - pipe build
  artifacts:
    paths:
      - dist/
      - "**/dist/"
  rules:
    - when: on_success
  tags:
    - docker
