---
stages:
  - install
  - build

include:
  - project: devops/pipes
    file: /templates/parent-pipeline-id.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/node-install.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/node-lint.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/node-test.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/node-build.gitlab-ci.yml
