variables:
  GITLAB_CI_ARCH: docker

lint:
  stage: build
  image: cenk1cenk2/pipe-node:${NODE_VERSION}
  script:
    - pipe run ${NODE_LINT_COMMAND}
  tags:
    - ${GITLAB_CI_ARCH}
  rules:
    - if: $NODE_LINT_COMMAND
