install:
  stage: install
  image: $CI_REGISTRY/devops/pipes/gitlab-pipes-node:${NODE_VERSION}
  script:
    - pipe install
  artifacts:
    paths:
      - node_modules/
      - "**/node_modules/"
  cache:
    paths:
      - node_modules/
      - .cache/
  rules:
    - when: on_success
  tags:
    - docker
