variables:
  PIPES_VERSION: latest
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  DOCKER_REGISTRY_PASSWORD: $CI_BUILD_TOKEN
  IMAGE_NAME: $CI_PROJECT_PATH/$DOCKER_IMAGE_NAME
  IMAGE_TAGS: $CI_BUILD_REF_NAME
  PARENT_DOWNLOAD_ARTIFACTS: "build"
  DOCKERFILE_CONTEXT: ""

stages:
  - prepare
  - docker

prepare:
  stage: prepare
  image: $CI_REGISTRY/bdsm/gitlab-pipes/gitlab-pipes-gl-artifacts:${PIPES_VERSION}
  script:
    - pipe
  artifacts:
    paths:
      - dist/
    expire_in: 30 minutes
  tags:
    - docker
  rules:
    - if: $PARENT_DOWNLOAD_ARTIFACTS

build-docker-image:
  stage: docker
  image: $CI_REGISTRY/bdsm/gitlab-pipes/gitlab-pipes-docker:${PIPES_VERSION}
  script:
    - pipe
  tags:
    - docker
