---
stages:
  - install
  - lint
  - version
  - publish

include:
  - project: devops/pipes
    file: /templates/v2/terraform-install.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/terraform-lint.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/semantic-release.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/terraform-publish.gitlab-ci.yml

tf-install:
  stage: install
  variables:
    TF_ROOT: $TF_MODULE_CWD
  extends: .tf-install
  needs: []

tf-lint:
  stage: lint
  extends: .tf-lint
  variables:
    TF_ROOT: $TF_MODULE_CWD
  needs:
    - tf-install
  dependencies:
    - tf-install

semantic-release:
  stage: version
  extends: .semantic-release
  needs: []

tf-publish:
  stage: publish
  extends: .tf-publish
  needs: []
