---
stages:
  - install
 # - lint
  - version
  - publish

include:
  - project: devops/pipes
    file: /templates/v2/terraform-install.gitlab-ci.yml

  #- project: devops/pipes
  #  file: /templates/v2/terraform-lint.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/semantic-release.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/terraform-publish.gitlab-ci.yml

tf-install:
  stage: install
  extends: .tf-install

#tf-lint:
  #stage: lint
  #extends: .tf-lint
  #dependencies:
   # - tf-install

semantic-release:
  stage: version
  extends: .semantic-release
  dependencies: []

tf-publish:
  stage: publish
  extends: .tf-publish
  dependencies:
    - semantic-release
