stages:
  - post

update-docker-hub-readme:
  stage: post
  image: cenk1cenk2/pipe-update-docker-hub-readme:latest
  script:
    - pipe
  variables:
    DOCKER_USERNAME: $DOCKERHUB_USERNAME
    DOCKER_PASSWORD: $DOCKER_HUB_API_PASSWORD
  only:
    refs:
      - master
      - main
      - tags
  tags:
    - docker
  when: always
