// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockhub

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.kilic.dev/devops/pipes/update-docker-hub-readme/hub"
)

// NewMockClientAdapter creates a new instance of MockClientAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAdapter {
	mock := &MockClientAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientAdapter is an autogenerated mock type for the ClientAdapter type
type MockClientAdapter struct {
	mock.Mock
}

type MockClientAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAdapter) EXPECT() *MockClientAdapter_Expecter {
	return &MockClientAdapter_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockClientAdapter
func (_mock *MockClientAdapter) Login(ctx context.Context, username string, password string) (string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAdapter_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockClientAdapter_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockClientAdapter_Expecter) Login(ctx any, username any, password any) *MockClientAdapter_Login_Call {
	return &MockClientAdapter_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockClientAdapter_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockClientAdapter_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientAdapter_Login_Call) Return(s string, err error) *MockClientAdapter_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClientAdapter_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, error)) *MockClientAdapter_Login_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReadme provides a mock function for the type MockClientAdapter
func (_mock *MockClientAdapter) UpdateReadme(ctx context.Context, token string, repository string, readme hub.Readme) (hub.Result, error) {
	ret := _mock.Called(ctx, token, repository, readme)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReadme")
	}

	var r0 hub.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, hub.Readme) (hub.Result, error)); ok {
		return returnFunc(ctx, token, repository, readme)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, hub.Readme) hub.Result); ok {
		r0 = returnFunc(ctx, token, repository, readme)
	} else {
		r0 = ret.Get(0).(hub.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, hub.Readme) error); ok {
		r1 = returnFunc(ctx, token, repository, readme)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAdapter_UpdateReadme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReadme'
type MockClientAdapter_UpdateReadme_Call struct {
	*mock.Call
}

// UpdateReadme is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - repository string
//   - readme hub.Readme
func (_e *MockClientAdapter_Expecter) UpdateReadme(ctx any, token any, repository any, readme any) *MockClientAdapter_UpdateReadme_Call {
	return &MockClientAdapter_UpdateReadme_Call{Call: _e.mock.On("UpdateReadme", ctx, token, repository, readme)}
}

func (_c *MockClientAdapter_UpdateReadme_Call) Run(run func(ctx context.Context, token string, repository string, readme hub.Readme)) *MockClientAdapter_UpdateReadme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 hub.Readme
		if args[3] != nil {
			arg3 = args[3].(hub.Readme)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientAdapter_UpdateReadme_Call) Return(result hub.Result, err error) *MockClientAdapter_UpdateReadme_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockClientAdapter_UpdateReadme_Call) RunAndReturn(run func(ctx context.Context, token string, repository string, readme hub.Readme) (hub.Result, error)) *MockClientAdapter_UpdateReadme_Call {
	_c.Call.Return(run)
	return _c
}
