---
spec:
  inputs:
    pipe_version:
      type: string
      default: latest
    tags:
      type: array
      default:
        - docker
    rules:
      type: array
      default:
        - interruptable: true
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_OPEN_MERGE_REQUESTS
          when: never
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
          variables:
            SEMANTIC_RELEASE_DRY_RUN: "true"

.semantic-release:
  image: cenk1cenk2/pipe-semantic-release:$[[inputs.pipe_version]]
  variables:
    GIT_AUTHOR_NAME: semantic-release [bot]
    GIT_AUTHOR_EMAIL: gitlab@kilic.dev
    GIT_COMMITTER_NAME: semantic-release [bot]
    GIT_COMMITTER_EMAIL: gitlab@kilic.dev
  script:
    - pipe
  artifacts:
    paths:
      - "**/.tags"
  rules: $[[input.rules]]
  tags: $[[input.tags]]
