---
spec:
  inputs:
    pipe_version:
      type: string
      default: latest
    tags:
      type: array
      default:
        - docker
    rules:
      type: array
      default:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_OPEN_MERGE_REQUESTS
          when: never
        - if: $CI_COMMIT_BRANCH
        - if: $CI_COMMIT_TAG

.tf-install:
  image: cenk1cenk2/pipe-terraform:$[[inputs.pipe_version]]
  script:
    - pipe install
  artifacts:
    paths:
      - "${TF_ROOT}/.terraform/"
      - "${TF_ROOT}/.terraform.lock.hcl"
  cache:
    - key: $CI_JOB_NAME_SLUG
      paths:
        - "**/.terraform/"
  rules: $[[inputs.rules]]
  tags: $[[inputs.tags]]
