// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockclient

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.kilic.dev/devops/pipes/github/client"
)

// NewMockApplicationClientAdapter creates a new instance of MockApplicationClientAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplicationClientAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplicationClientAdapter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockApplicationClientAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockApplicationClientAdapter is an autogenerated mock type for the ApplicationClientAdapter type
type MockApplicationClientAdapter struct {
	mock.Mock
}

type MockApplicationClientAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplicationClientAdapter) EXPECT() *MockApplicationClientAdapter_Expecter {
	return &MockApplicationClientAdapter_Expecter{mock: &_m.Mock}
}

// CreateCommitStatus provides a mock function for the type MockApplicationClientAdapter
func (_mock *MockApplicationClientAdapter) CreateCommitStatus(ctx context.Context, token string, repository string, sha string, status client.CommitStatus) error {
	ret := _mock.Called(ctx, token, repository, sha, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateCommitStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, client.CommitStatus) error); ok {
		r0 = returnFunc(ctx, token, repository, sha, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplicationClientAdapter_CreateCommitStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCommitStatus'
type MockApplicationClientAdapter_CreateCommitStatus_Call struct {
	*mock.Call
}

// CreateCommitStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - repository string
//   - sha string
//   - status client.CommitStatus
func (_e *MockApplicationClientAdapter_Expecter) CreateCommitStatus(ctx any, token any, repository any, sha any, status any) *MockApplicationClientAdapter_CreateCommitStatus_Call {
	return &MockApplicationClientAdapter_CreateCommitStatus_Call{Call: _e.mock.On("CreateCommitStatus", ctx, token, repository, sha, status)}
}

func (_c *MockApplicationClientAdapter_CreateCommitStatus_Call) Run(run func(ctx context.Context, token string, repository string, sha string, status client.CommitStatus)) *MockApplicationClientAdapter_CreateCommitStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 client.CommitStatus
		if args[4] != nil {
			arg4 = args[4].(client.CommitStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockApplicationClientAdapter_CreateCommitStatus_Call) Return(err error) *MockApplicationClientAdapter_CreateCommitStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplicationClientAdapter_CreateCommitStatus_Call) RunAndReturn(run func(ctx context.Context, token string, repository string, sha string, status client.CommitStatus) error) *MockApplicationClientAdapter_CreateCommitStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInstallationToken provides a mock function for the type MockApplicationClientAdapter
func (_mock *MockApplicationClientAdapter) CreateInstallationToken(ctx context.Context, jwt string, installation string, request client.TokenRequest) (string, error) {
	ret := _mock.Called(ctx, jwt, installation, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstallationToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.TokenRequest) (string, error)); ok {
		return returnFunc(ctx, jwt, installation, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.TokenRequest) string); ok {
		r0 = returnFunc(ctx, jwt, installation, request)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.TokenRequest) error); ok {
		r1 = returnFunc(ctx, jwt, installation, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApplicationClientAdapter_CreateInstallationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstallationToken'
type MockApplicationClientAdapter_CreateInstallationToken_Call struct {
	*mock.Call
}

// CreateInstallationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - jwt string
//   - installation string
//   - request client.TokenRequest
func (_e *MockApplicationClientAdapter_Expecter) CreateInstallationToken(ctx any, jwt any, installation any, request any) *MockApplicationClientAdapter_CreateInstallationToken_Call {
	return &MockApplicationClientAdapter_CreateInstallationToken_Call{Call: _e.mock.On("CreateInstallationToken", ctx, jwt, installation, request)}
}

func (_c *MockApplicationClientAdapter_CreateInstallationToken_Call) Run(run func(ctx context.Context, jwt string, installation string, request client.TokenRequest)) *MockApplicationClientAdapter_CreateInstallationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.TokenRequest
		if args[3] != nil {
			arg3 = args[3].(client.TokenRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockApplicationClientAdapter_CreateInstallationToken_Call) Return(s string, err error) *MockApplicationClientAdapter_CreateInstallationToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockApplicationClientAdapter_CreateInstallationToken_Call) RunAndReturn(run func(ctx context.Context, jwt string, installation string, request client.TokenRequest) (string, error)) *MockApplicationClientAdapter_CreateInstallationToken_Call {
	_c.Call.Return(run)
	return _c
}
